name: my_web_page
description: "My web page."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/social/
    - assets/icons/projects/
    - assets/icons/companies/
    - assets/icons/skills/
    - assets/icons/education/
    - assets/images/
