name: Build and Deploy

permissions:
  checks: write
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_branch:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: github.head_ref != 'development'
        run: |
          echo "ERROR: You can only merge into 'main' from the 'development' branch."
          echo "Your source branch is: ${{ github.head_ref }}"
          exit 1

  build_and_deploy:
    needs: [check_branch]
    if: |
      always() && 
      (needs.check_branch.result == 'success' || needs.check_branch.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Web
        run: flutter build web --release --base-href "/"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STUDIO_7308954666_4CD06 }}'
          projectId: studio-7308954666-4cd06
          # Если main -> live. Если development -> канал "development".
          channelId: ${{ github.ref_name == 'main' && 'live' || 'development' }}
